---
# Meta information for Cisco Router Role
galaxy_info:
  role_name: cisco_router
  author: Infrastructure Orchestrator
  description: Production Cisco router configuration and management
company: Network
  license: MIT
  min_ansible_version: "2.12"
  
  platforms:
    - name: IOS
      versions:
        - "15.x"
        - "16.x"
        - "17.x"
  
  galaxy_tags:
    - cisco
    - router
    - network
    - infrastructure
    - production

dependencies:
  - role: security_hardening
    when: apply_security_hardening | default(true)

collections:
  - cisco.ios
  - ansible.netcommon